APPLICATION=BaseSys_rename

BOARD ?= native

USEMODULE += periph_i2c

USEMODULE += xtimer

FEATURES_REQUIRED += periph_hwrng

FEATURES_REQUIRED += periph_i2c

RIOTBASE ?= $(CURDIR)/../../RIOT

DEVELHELP ?= 1

include $(RIOTBASE)/Makefile.include

