APPLICATION=BaseSys_rename

BOARD ?= native

FEATURES_REQUIRED = periph_spi

USEMODULE += shell

USEMODULE += shell_commands

USEMODULE += ps

USEMODULE += xtimer

USEMODULE += printf_float

RIOTBASE ?= $(CURDIR)/../../RIOT

DEVELHELP ?= 1

include $(RIOTBASE)/Makefile.include


