APPLICATION=BaseSys_rename

BOARD ?= native

USEMODULE += shell

USEMODULE += shell_commands

USEMODULE += ps

USEMODULE += xtimer

RIOTBASE ?= $(CURDIR)/../../RIOT

DEVELHELP ?= 1

include $(RIOTBASE)/Makefile.include


